[package]
name = "mash"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.5", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
paris = { version = "1.5", features = ["timestamps", "macros"] }
